#! /bin/bash
# Look for devices in local network with SSH port open.
# Try to open connection.
# Usage find_ssh_server user

# Get the IP of devices in the network.
for each in `nmap -sP 192.168.0.101/24 | grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' `
do

    echo  $each
    nc -w 2 $each 22 # Get those with SSH port 22 open. 2 sec of timeout.

    if [ $? -eq 0 ]
    then
        break;       # Break the loop when found.
    fi

done

# Open SSH connection
ssh $each -l $1
